const fruitVegDb = [
  { name: "Apple", avgWeightKg: 0.18 },
  { name: "Apricot", avgWeightKg: 0.035 },
  { name: "Artichoke", avgWeightKg: 0.4 },
  { name: "Asparagus", avgWeightKg: 0.02 },
  { name: "Avocado", avgWeightKg: 0.25 },
  { name: "Banana", avgWeightKg: 0.15 },
  { name: "Beetroot", avgWeightKg: 0.3 },
  { name: "Bell Pepper", avgWeightKg: 0.18 },
  { name: "Blackberry", avgWeightKg: 0.004 },
  { name: "Blueberry", avgWeightKg: 0.0005 },
  { name: "Broccoli", avgWeightKg: 0.35 },
  { name: "Brussels Sprouts", avgWeightKg: 0.02 },
  { name: "Cabbage", avgWeightKg: 1.0 },
  { name: "Carrot", avgWeightKg: 0.07 },
  { name: "Cauliflower", avgWeightKg: 0.5 },
  { name: "Celery", avgWeightKg: 0.4 },
  { name: "Cherry", avgWeightKg: 0.008 },
  { name: "Chili Pepper", avgWeightKg: 0.01 },
  { name: "Clementine", avgWeightKg: 0.1 },
  { name: "Corn", avgWeightKg: 0.3 },
  { name: "Cucumber", avgWeightKg: 0.25 },
  { name: "Date", avgWeightKg: 0.007 },
  { name: "Eggplant", avgWeightKg: 0.3 },
  { name: "Fennel", avgWeightKg: 0.4 },
  { name: "Fig", avgWeightKg: 0.05 },
  { name: "Garlic", avgWeightKg: 0.05 },
  { name: "Ginger", avgWeightKg: 0.05 },
  { name: "Grape", avgWeightKg: 0.005 },
  { name: "Green Beans", avgWeightKg: 0.01 },
  { name: "Green Peas", avgWeightKg: 0.01 },
  { name: "Honeydew Melon", avgWeightKg: 1.5 },
  { name: "Jalapeno", avgWeightKg: 0.02 },
  { name: "Kiwi", avgWeightKg: 0.08 },
  { name: "Kohlrabi", avgWeightKg: 0.3 },
  { name: "Leek", avgWeightKg: 0.2 },
  { name: "Lemon", avgWeightKg: 0.1 },
  { name: "Lettuce", avgWeightKg: 0.3 },
  { name: "Lime", avgWeightKg: 0.07 },
  { name: "Lychee", avgWeightKg: 0.02 },
  { name: "Mango", avgWeightKg: 0.35 },
  { name: "Melon", avgWeightKg: 1.5 },
  { name: "Mushroom", avgWeightKg: 0.02 },
  { name: "Nectarine", avgWeightKg: 0.15 },
  { name: "Okra", avgWeightKg: 0.02 },
  { name: "Onion", avgWeightKg: 0.15 },
  { name: "Orange", avgWeightKg: 0.2 },
  { name: "Papaya", avgWeightKg: 0.5 }
];
